version: '3.7'

networks:
  shopware:

services:
  server:
    build: ./.docker/nginx
    container_name: danneg_sw6_nginx
    volumes:
      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/conf/sites-enabled:/usr/local/bin/nginx/sites-enabled
      - ./.docker/nginx/logs:/var/log/nginx
      - ./src:/var/www/shopware
    ports:
      - 8000:80
    links:
      - php
      - elasticsearch
    tty: true
    env_file:
      - .env
    networks:
      - shopware

  php:
    build: ./.docker/php
    container_name: danneg_sw6_php8.1
    volumes:
      - ./.docker/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/logs:/var/log/php
      - ./src:/var/www/shopware
    ports:
      - 9000
    links:
      - mysql
      - mailhog
      - memcached
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=sw6.local"
    networks:
      - shopware

  mysql:
    build: .docker/mysql
    volumes:
      - ./.docker/mysql/conf/:/etc/mysql/mysql.conf/
      - db-local-sw6:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: app
      MYSQL_PASSWORD: shopware
    ports:
      - 3306
    networks:
      - shopware

  mailhog:
    image: mailhog/mailhog
    networks:
      shopware:
        aliases:
          - mailhog

  memcached:
    image: memcached:1.6
    container_name: sw6_memcached1.6
    networks:
      - shopware
    ports:
      - 11211

  elasticsearch:
    image: elastic/elasticsearch:7.8.0
    container_name: danneg_sw6_es
    networks:
      shopware:
        aliases:
          - elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=shopware-cluster
      - bootstrap.memory_lock=true
      - "ES_HEAP_SIZE=512m"
      - "MAX_LOCKED_MEMORY=100000"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.docker/es/log:/opt/elasticsearch/volatile/log
      - ./.docker/es/data:/opt/elasticsearch/volatile/data
    ports:
      - 9200
      - 9300

volumes:
  db-local-sw6:
    external: true